# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: stage1
    jobs:
    - job: task1
      steps:
      - script: echo Building!
  - stage: stage2
    dependsOn:
    - stage1
    jobs:
    - job: task2
      steps:
      - script: echo Building!
  - stage: stage3
    dependsOn:
    - stage1
    jobs:
    - job: task3
      steps:
      - script: echo Building!
  - stage: stage4
    dependsOn: 
    - stage3
    jobs:
    - job: task4
      steps:
      - script: echo Building!
  - stage: stage5
    dependsOn:
    - stage3
    - stage4
    jobs:
    - job: task5
      steps:
      - script: echo Building!
  - stage: stage6
    dependsOn:
    - stage2
    - stage5
    jobs:
    - job: task6
      steps:
      - script: echo Building!