# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest
stages:
  - stage: stage-1
    jobs:
    - job: task-1
      steps:
      - script: echo Building!
  - stage: stage-2
    jobs:
    - job: task-2
      steps:
      - script: echo Building!
  - stage: stage-3
    jobs:
    - job: task-3
      steps:
      - script: echo Building!
  - stage: stage-4
    dependsOn: 
    - stage-3
    jobs:
    - job: task-4
      steps:
      - script: echo Building!
  - stage: stage-5
    dependsOn:
    - stage-3
    - stage-4
    jobs:
    - job: task-5
      steps:
      - script: echo Building!