# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: BuildJob
    steps:
    - script: echo Building!
- stage: Test1
  jobs:
  - job: TestJob
    steps:
    - script: echo Test!
  dependsOn: [Build]
- stage: Test2
  jobs:
  - job: TestOnWindows
    steps:
    - script: echo Testing on Windows!
  - job: TestOnLinux
    steps:
    - script: echo Testing on Linux!
  dependsOn: [Build]
- stage: Deploy
  jobs:
  - job: Deploy
    steps:
    - script: echo Deploying the code!

# jobs:
#   - job: waitForValidation
#     displayName: Wait for external validation
#     pool: server
#     timeoutInMinutes: 4320 # job times out in 3 days
#     steps:
#     - task: ManualValidation@0
#       timeoutInMinutes: 1440 # task times out in 1 day
#       inputs:
#         notifyUsers: 416482742@qq.com
#         instructions: 'Please validate the build configuration and resume'
#         onTimeout: 'resume'
#   - job: job2
#     steps:
#     - script: echo Hello, world!
#     displayName: 'Run a one-line script'
